
# **Question No 01**

Write a function called create_word_count that takes a list of strings and returns a dictionary where:

Keys are unique words from the list.
Values are the count of occurrences of each word.

**Exmple:**
words = ['apple', 'banana', 'apple', 'cherry', 'banana', 'apple']
result = create_word_count(words)
print(result)  # {'apple': 3, 'banana': 2, 'cherry': 1}

In [1]:
def create_word_count(words):
    word_count = {}
    for word in words:
        if word in word_count:
            word_count[word] += 1
        else:
            word_count[word] = 1
    return word_count

words = ['apple', 'banana', 'apple', 'cherry', 'banana', 'apple']
result = create_word_count(words)
print(result)

{'apple': 3, 'banana': 2, 'cherry': 1}

# **Question No 02**

Write a function called sort_by_key that takes a list of dictionaries and a key to sort by.

The function should return a new list sorted by the given key in ascending order.
If the key doesnâ€™t exist in a dictionary, ignore that dictionary.

**Exmple:**

data = [{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age': 22}, {'name': 'Charlie', 'age': 30}]
sorted_data = sort_by_key(data, 'age')
print(sorted_data)  
# [{'name': 'Bob', 'age': 22}, {'name': 'Alice', 'age': 25}, {'name': 'Charlie', 'age': 30}]

In [3]:
def sort_by_key(data, key):
    filtered_data = [d for d in data if key in d]
    for i in range(len(filtered_data)):
        for j in range(i + 1, len(filtered_data)):
            if filtered_data[i][key] > filtered_data[j][key]:
                filtered_data[i], filtered_data[j] = filtered_data[j], filtered_data[i]
    return filtered_data

data = [{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age': 22}, {'name': 'Charlie', 'age': 30}]
sorted_data = sort_by_key(data, 'age')
print(sorted_data)

[{'name': 'Bob', 'age': 22}, {'name': 'Alice', 'age': 25}, {'name': 'Charlie', 'age': 30}]

# **Question No 03**

Write a function called filter_dict that takes a dictionary and a value threshold as arguments.

The function should return a new dictionary containing only the key-value pairs where the value is greater than the threshold.

**Exmple:**

scores = {'Alice': 85, 'Bob': 90, 'Charlie': 78, 'David': 92}
filtered_scores = filter_dict(scores, 80)
print(filtered_scores)  # {'Alice': 85, 'Bob': 90, 'David': 92}

In [4]:
def filter_dict(data, threshold):
    filtered = {}
    for key, value in data.items():
        if value > threshold:
            filtered[key] = value
    return filtered

scores = {'Alice': 85, 'Bob': 90, 'Charlie': 78, 'David': 92}
filtered_scores = filter_dict(scores, 80)
print(filtered_scores)

{'Alice': 85, 'Bob': 90, 'David': 92}

# **Question No 04**

Write a function called find_common_keys that takes two dictionaries and returns a list of keys that are common to both.


**Exmple:**

dict1 = {'a': 1, 'b': 2, 'c': 3}
dict2 = {'b': 4, 'c': 5, 'd': 6}
common_keys = find_common_keys(dict1, dict2)
print(common_keys)  # ['b', 'c']

In [6]:
def find_common_keys(dict1, dict2):
    common_keys = []
    for key in dict1:
        if key in dict2:
            common_keys.append(key)
    return common_keys

dict1 = {'a': 1, 'b': 2, 'c': 3}
dict2 = {'b': 4, 'c': 5, 'd': 6}
common_keys = find_common_keys(dict1, dict2)
print(common_keys)

['b', 'c']

# **Question No 5**

Write a function called update_grades that takes a list of dictionaries (representing students with their grades) and updates the grade of a student if their name matches the given name.


**Exmple:**

students = [{'name': 'Alice', 'grade': 85}, {'name': 'Bob', 'grade': 90}]
updated_students = update_grades(students, 'Bob', 95)
print(updated_students)  
# [{'name': 'Alice', 'grade': 85}, {'name': 'Bob', 'grade': 95}]

In [7]:
def update_grades(students, name, new_grade):
    for student in students:
        if student['name'] == name:
            student['grade'] = new_grade
    return students

students = [{'name': 'Alice', 'grade': 85}, {'name': 'Bob', 'grade': 90}]
updated_students = update_grades(students, 'Bob', 95)
print(updated_students)

[{'name': 'Alice', 'grade': 85}, {'name': 'Bob', 'grade': 95}]

# **Question No 6**

Write a function called merge_lists_to_dict that takes two lists of equal length:

The first list contains keys.
The second list contains values.
The function should return a dictionary created by merging these lists.

**Exmple:**
keys = ['name', 'age', 'city']
values = ['Alice', 25, 'New York']
result = merge_lists_to_dict(keys, values)
print(result)  # {'name': 'Alice', 'age': 25, 'city': 'New York'}

In [8]:
def merge_lists_to_dict(keys, values):
    return {keys[i]: values[i] for i in range(len(keys))}

keys = ['name', 'age', 'city']
values = ['Alice', 25, 'New York']
result = merge_lists_to_dict(keys, values)
print(result)

{'name': 'Alice', 'age': 25, 'city': 'New York'}